services:
  db:
    image: postgres:16
    container_name: plinko-db
    restart: always
    environment:
      POSTGRES_USER: plinko
      POSTGRES_PASSWORD: sandip
      POSTGRES_DB: plinko
    volumes:
      - plinko_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    build: .
    container_name: plinko-app
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://plinko:sandip@db:5432/plinko

volumes:
  plinko_pgdata: